matrix:
  PHP_TAG:
  - php74
  - php80
  - php81
  - php82
steps:
  image-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ gitea_username, gitea_token ]
    settings:
      repo: git.zyphi.co/deploy/php-nginx
      registry: git.zyphi.co
      username:
        from_secret: gitea_username
      password:
        from_secret: gitea_token
      context: ./manifest/images
      dockerfile: ./manifest/images/${PHP_TAG}/Dockerfile
      tag: ${PHP_TAG}
when:
  - event:
    - manual
