matrix:
  PHP_TAG:
  - php80
  - php81
  - php82
  - php83
steps:
  image-build:
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      repo: docker.io/ccarney16/php-nginx
      context: ./manifest/images
      dockerfile: ./manifest/images/${PHP_TAG}/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
      - ${PHP_TAG}
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token

when:
- event: [ manual ]
